# Generated by Django 5.1.6 on 2025-03-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_usuario_is_active_remove_usuario_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
